### ISSUE TITLE
Maximum BigInt size exceeded

### ISSUE THREAD

**Issue by futpib** [GoogleChromeLabs/jsbi#34]
```bash
→ node -e "console.log(BigInt('12341234123412341234'))"

12341234123412341234n
```

```bash
→ node -e "new (require('jsbi'))('12341234123412341234')"

RangeError: Maximum BigInt size exceeded
    at new JSBI (/home/roman-geints/tmp/node_modules/jsbi/dist/jsbi-cjs.js:1:85)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:126:20)
    at Object.runInThisContext (vm.js:316:38)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at evalScript (internal/process/execution.js:80:25)
    at internal/main/eval_string.js:23:3
```

Does not this defeat the purpose of BigInt?

README claims this is "an implementation of the official ECMAScript BigInt proposal", this is clearly not the case.

**Comment by jakobkummerow** [comment]
Please continue reading past the first line of the README ;-)
Just a few lines further down, you'll find the "Usage" section, which shows how to create (and print) a JSBI BigInt:

````
console.log(JSBI.BigInt('12341234123412341234').toString());  // works just fine.
````

Don't use `new JSBI(...)`.

**Comment by futpib** [comment]
Oh, sorry.
